W-17457827: JPMS support for the RevAPI plugin.
mulesoft/mule-revapi-extension pull request #172
Opened 2024-12-27 18:46 UTC by IvanAndresFritzler

2024-12-30 14:09 UTC, fsgonz approved these changes, later dismissed
LGTM in general.

2025-01-03 15:00 UTC, elrodro83 requested changes

2025-01-03 15:00 UTC, elrodro83 commented on src/main/java/org/mule/tools/revapi/ExportPackageFilter.java
> +        if (!addMuleModuleSystemExportedPackages(archive, exportedPackages)) {
use && instead of nested ifs

2025-01-03 15:00 UTC, elrodro83 commented on src/main/java/org/mule/tools/revapi/ExportPackageFilter.java
> +    if (isMixedMode() || isMuleMode()) {
shouldn't `isMuleMode` checked for mixed mode as well?

2025-01-03 15:00 UTC, elrodro83 commented on src/main/java/org/mule/tools/revapi/ExportPackageFilter.java
> +    if (isJavaMode() || isMixedMode()) {
shouldn't isJavaMode checked for mixed mode as well?

2025-01-03 15:00 UTC, elrodro83 commented on src/main/java/org/mule/tools/revapi/ExportedPackages.java
> +  void logExportedPackages();
why this is weird... by the name this seems to be a value object... why does it have logging behaviour?

2025-01-03 15:00 UTC, elrodro83 commented on src/main/java/org/mule/tools/revapi/ExportedPackages.java
> +  boolean isExported(String packageName);
add javadocs

2025-01-03 15:00 UTC, elrodro83 commented on src/main/java/org/mule/tools/revapi/JavaModuleSystemExportedPackages.java
> +        return Optional.of(moduleReferences.iterator().next());
static import

2025-01-03 15:00 UTC, elrodro83 commented on src/main/java/org/mule/tools/revapi/JavaModuleSystemExportedPackages.java
> +      return ((File) archiveFile.get(archive)).toPath();
`archive.getName()`?

2025-01-28 13:15 UTC, closed without merging